### ISSUE TITLE
pipeline gives an error message

### ISSUE THREAD

**Issue by temuller** [cinserra/FDST#1]
when I run the pipeline with a fits file of an object (v_e_20190213_57_1_0_0.fits) I get the next error message:

List the spectra (space separated list) to use: v_e_20190213_57_1_0_0.fits
v_e_20190213_57_1_0_0.fits[3] -> spectrum.fits
Killing IRAF task `imcopy'
Traceback (most recent call last):
 File "/home/tomas/anaconda3/envs/iraf27/bin/FDSTfast", line 85, in <module>
   iraf.imcopy(_snname + "[3]",'spectrum.fits')
 File "/home/tomas/anaconda3/envs/iraf27/lib/python2.7/site-packages/pyraf/iraftask.py", line 767, in __call__
   return self.run(*args, **kw)
 File "/home/tomas/anaconda3/envs/iraf27/lib/python2.7/site-packages/pyraf/iraftask.py", line 359, in run
   self._run(redirKW, specialKW)
 File "/home/tomas/anaconda3/envs/iraf27/lib/python2.7/site-packages/pyraf/iraftask.py", line 811, in _run
   "\n"+str(value))
stsci.tools.irafglobals.IrafError: Error running IRAF task imcopy
IRAF task terminated abnormally
ERROR (827, "Cannot open image (v_e_20190213_57_1_0_0.fits[3])")

**Comment by marianarubetdacosta** [comment]
I´m dealing with the same problem. How can I resolve this error?

**Comment by temuller** [comment]
This was a long time ago, I don't remember if I was able to fix it or not. Sorry.

**Comment by marianarubetdacosta** [comment]
Ok! Thank u =)

Em ter, 20 de abr de 2021 05:23, Tomás E. Müller Bravo <
***@***.***> escreveu:

**Comment by cinserra** [comment]
HI both, that is due to the fact that they have likely change the spectra dimension, i.e. the entry [3] is not the counts vs pixel spectrum and the entry [3] is no longer used anymore. I do not have recent LT spectra to check but I could try to test it in the next month or so
